### ISSUE TITLE
Add brief command

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-v3#11]
Refer to https://github.com/drph4nt0m/avbot repo for this task.

**Comment by ransbachm** [comment]
I would like to do this 😃

**Comment by drph4nt0m** [comment]
@ransbachm sure. Please proceed.

**Comment by ransbachm** [comment]
Can you assign 😄 ?

**Comment by ransbachm** [comment]
@drph4nt0m 
Draft PR done, almost complete, please review and link #35. 😎🎉

**Comment by ransbachm** [comment]
Please link #35

**Comment by drph4nt0m** [comment]
It is already link.

**Comment by ransbachm** [comment]
![image](https://user-images.githubusercontent.com/25692733/95778718-f9456800-0cc8-11eb-9baf-ca63d596309c.png)

Ok, weird mine says none xD

**Comment by drph4nt0m** [comment]
@ransbachm ohh sorry. Done.
