### ISSUE TITLE
add zulu command

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-v3#16]
Refer to https://github.com/drph4nt0m/avbot repo for this task.

**Comment by radiantly** [comment]
Hey, could I take a go at this?

**Comment by drph4nt0m** [comment]
@radiantly sure

**Comment by drph4nt0m** [comment]
Hey @radiantly,

Any update on this?

**Comment by radiantly** [comment]
@drph4nt0m Sorry, slightly busy past few days. I'm good now, will get the PR ready :+1:
