### ISSUE TITLE
Fix dockerization

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-v3#27]
The current dockerfile has issues accessing env vars. I have tried the yaml approach as well but that was having issues sending voice message for the atis-voice command.

**Comment by Fedelaus** [comment]
@drph4nt0m can you please provide an example of what kind of env var you wish to use within the Dockerfile?

**Comment by drph4nt0m** [comment]
@Fedelaus just added [.env.example](https://github.com/drph4nt0m/avbot-v3/blob/master/.env.example)

**Comment by abxsantos** [comment]
Using a  --env-file ./.env flag during the docker run step isn't working?

**Comment by drph4nt0m** [comment]
@abxsantos getting `node: bad option: --env-file` error

**Comment by Fedelaus** [comment]
Addressed this @ https://github.com/drph4nt0m/avbot-v3/pull/29

**Comment by abxsantos** [comment]
@drph4nt0m I don't know if you are running the docker run command this way, but maybe this will help you out, since I don't think moving a .env file a good idea. 

https://stackoverflow.com/questions/59350179/cant-set-environment-variables-with-docker-run-e-or-env-file-option
