### ISSUE TITLE
Nodemon does not restart bot

### ISSUE THREAD

**Issue by ransbachm** [drph4nt0m/avbot-v3#42]
# Nodemon does not restart bot
Not really a bug, but nodemon will not restart the bot if just a command (.js) file was edited.

# Steps to reproduce the behavior:

1. npm run dev
2. Edit any command
3. Bot won't restart

# Expected behavior
Bot should restart.

# Desktop
OS: Windows 10 USING (WSL2 Ubuntu)
Browser -
Version: any new
# 
Probably a discussion to be had.

**Comment by drph4nt0m** [comment]
It should work. Tested.
